---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpngx-deployment
spec:
  replicas: 14
  selector:
    matchLabels:
      app: phpngx
  template:
    metadata:
      labels:
        app: phpngx
    spec:
      containers:
      - image: frickler24/phpngx
        name: phpngx-deployment
        ports:
        - containerPort: 80
          name: meinport
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: "0.4"
            memory: "300M"
          requests:
            cpu: "0.3"
            memory: "100M"
        livenessProbe:
          httpGet:
            path: /test.php
            port: meinport
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /test.php
            port: meinport
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: phpngx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: phpngx
  ports:
  - protocol: TCP
    nodePort: 30666
    port: 80
    targetPort: 80
