---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: av-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: av-server
  template:
    metadata:
      labels:
        app: av-server
    spec:
      containers:
      - image: frickler24/av-server:latest
        name: av-server-container
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: av-server-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: av-server
  ports:
  - protocol: TCP
#    nodePort: 30000
    port: 3000
#    targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: av-server
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: av-server-service 
          servicePort: 3000
